# docker compose -f docker-compose_financial.yml --env-file ./compose.env up -d
# docker compose -f docker-compose_financial.yml --env-file ./compose.env up -d bot_financial_trading
version: '3.9'

services:
  data_provider_mt4:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: data_provider_mt4
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      BROKER_FINANCIAL: darwinex
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/financial_trading/data_realtime_financial.py

  data_provider_ib:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: data_provider_ib
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      BROKER_FINANCIAL: ib
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/financial_trading/data_realtime_financial.py

  bot_financial_trading:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: bot_financial_trading
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: ib_order
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/portfolio_production.py

  broker_mt4:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: broker_mt4
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: darwinex_order
      BROKER_FINANCIAL: darwinex
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/financial_trading/broker_financial.py

  broker_ib:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: broker_ib
    volumes:
      - ..:/app
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      ROUTING_KEY: ib_order
      BROKER_FINANCIAL: ib
    networks:
      - smartbots_networks
    command: python -u ./src/application/bots/financial_trading/broker_financial_ib.py

  telegram_financial:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: telegram_financial
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
      TRADING_TYPE_DOCKER: financial
      BROKER_FINANCIAL: darwinex
    command: python -u ./src/application/bots/telegram_bot.py

  update_mongodb_financial:
    build:
      context: .
      dockerfile: smartbot-python.dockerfile
    hostname: update_mongodb_financial
    volumes:
      - ..:/app
    networks:
      - smartbots_networks
    environment:
      AM_I_IN_A_DOCKER_CONTAINER: 1
    command: python -u ./src/infrastructure/update_mongodb_financial.py

networks:
  smartbots_networks:
    ipam:
      config:
        - subnet: 172.20.0.0/24